// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  proxyflarePluginSidebar: [
    {
      type: "category",
      label: "Proxyflare for Pages",
      items: [{ type: "autogenerated", dirName: "proxyflare/plugin" }],
    },
  ],
  proxyflarePlatformSidebar: [
    {
      type: "category",
      label: "Proxyflare Platform",
      items: [{ type: "autogenerated", dirName: "proxyflare/platform" }],
    },
  ],
  edgeflarePluginSidebar: [
    {
      type: "category",
      label: "Edgeflare for Pages",
      items: [{ type: "autogenerated", dirName: "edgeflare/plugin" }],
    },
  ],
  edgeflarePlatformSidebar: [
    {
      type: "category",
      label: "Edgeflare Platform",
      items: [{ type: "autogenerated", dirName: "edgeflare/platform" }],
    },
  ],
}

module.exports = sidebars
